export const regionesData = [
  { id: `2`, nombre: `ANTOFAGASTA`, value: `2`, label: `ANTOFAGASTA` },
  {
    id: `15`,
    nombre: `ARICA Y PARINACOTA`,
    value: `15`,
    label: `ARICA Y PARINACOTA`,
  },
  { id: `3`, nombre: `ATACAMA`, value: `3`, label: `ATACAMA` },
  {
    id: `11`,
    nombre: `AYSÉN DEL GRAL. CARLOS IBÁÑEZ DEL CAMPO`,
    value: `11`,
    label: `AYSÉN DEL GRAL. CARLOS IBÁÑEZ DEL CAMPO`,
  },
  { id: `8`, nombre: `BIOBÍO`, value: `8`, label: `BIOBÍO` },
  { id: `4`, nombre: `COQUIMBO`, value: `4`, label: `COQUIMBO` },
  { id: `9`, nombre: `LA ARAUCANÍA`, value: `9`, label: `LA ARAUCANÍA` },
  {
    id: `6`,
    nombre: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    value: `6`,
    label: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
  },
  { id: `10`, nombre: `LOS LAGOS`, value: `10`, label: `LOS LAGOS` },
  { id: `14`, nombre: `LOS RÍOS`, value: `14`, label: `LOS RÍOS` },
  {
    id: `12`,
    nombre: `MAGALLANES Y DE LA ANTÁRTICA CHILENA`,
    value: `12`,
    label: `MAGALLANES Y DE LA ANTÁRTICA CHILENA`,
  },
  { id: `7`, nombre: `MAULE`, value: `7`, label: `MAULE` },
  {
    id: `13`,
    nombre: `METROPOLITANA DE SANTIAGO`,
    value: `13`,
    label: `METROPOLITANA DE SANTIAGO`,
  },
  { id: `1`, nombre: `TARAPACÁ`, value: `1`, label: `TARAPACÁ` },
  { id: `5`, nombre: `VALPARAÍSO`, value: `5`, label: `VALPARAÍSO` },
  { id: `16`, nombre: `ÑUBLE`, value: `16`, label: `ÑUBLE` },
]

export const comunasByRegionIdData = {
  '1': [
    {
      id: `1107`,
      nombre: `ALTO HOSPICIO`,
      value: `1107`,
      label: `ALTO HOSPICIO`,
      cod_reg: `1`,
      nom_reg: `TARAPACÁ`,
    },
    {
      id: `1402`,
      nombre: `CAMIÑA`,
      value: `1402`,
      label: `CAMIÑA`,
      cod_reg: `1`,
      nom_reg: `TARAPACÁ`,
    },
    {
      id: `1403`,
      nombre: `COLCHANE`,
      value: `1403`,
      label: `COLCHANE`,
      cod_reg: `1`,
      nom_reg: `TARAPACÁ`,
    },
    {
      id: `1404`,
      nombre: `HUARA`,
      value: `1404`,
      label: `HUARA`,
      cod_reg: `1`,
      nom_reg: `TARAPACÁ`,
    },
    {
      id: `1101`,
      nombre: `IQUIQUE`,
      value: `1101`,
      label: `IQUIQUE`,
      cod_reg: `1`,
      nom_reg: `TARAPACÁ`,
    },
    {
      id: `1405`,
      nombre: `PICA`,
      value: `1405`,
      label: `PICA`,
      cod_reg: `1`,
      nom_reg: `TARAPACÁ`,
    },
    {
      id: `1401`,
      nombre: `POZO ALMONTE`,
      value: `1401`,
      label: `POZO ALMONTE`,
      cod_reg: `1`,
      nom_reg: `TARAPACÁ`,
    },
  ],
  '2': [
    {
      id: `2101`,
      nombre: `ANTOFAGASTA`,
      value: `2101`,
      label: `ANTOFAGASTA`,
      cod_reg: `2`,
      nom_reg: `ANTOFAGASTA`,
    },
    {
      id: `2201`,
      nombre: `CALAMA`,
      value: `2201`,
      label: `CALAMA`,
      cod_reg: `2`,
      nom_reg: `ANTOFAGASTA`,
    },
    {
      id: `2302`,
      nombre: `MARÍA ELENA`,
      value: `2302`,
      label: `MARÍA ELENA`,
      cod_reg: `2`,
      nom_reg: `ANTOFAGASTA`,
    },
    {
      id: `2102`,
      nombre: `MEJILLONES`,
      value: `2102`,
      label: `MEJILLONES`,
      cod_reg: `2`,
      nom_reg: `ANTOFAGASTA`,
    },
    {
      id: `2202`,
      nombre: `OLLAGÜE`,
      value: `2202`,
      label: `OLLAGÜE`,
      cod_reg: `2`,
      nom_reg: `ANTOFAGASTA`,
    },
    {
      id: `2203`,
      nombre: `SAN PEDRO DE ATACAMA`,
      value: `2203`,
      label: `SAN PEDRO DE ATACAMA`,
      cod_reg: `2`,
      nom_reg: `ANTOFAGASTA`,
    },
    {
      id: `2103`,
      nombre: `SIERRA GORDA`,
      value: `2103`,
      label: `SIERRA GORDA`,
      cod_reg: `2`,
      nom_reg: `ANTOFAGASTA`,
    },
    {
      id: `2104`,
      nombre: `TALTAL`,
      value: `2104`,
      label: `TALTAL`,
      cod_reg: `2`,
      nom_reg: `ANTOFAGASTA`,
    },
    {
      id: `2301`,
      nombre: `TOCOPILLA`,
      value: `2301`,
      label: `TOCOPILLA`,
      cod_reg: `2`,
      nom_reg: `ANTOFAGASTA`,
    },
  ],
  '3': [
    {
      id: `3302`,
      nombre: `ALTO DEL CARMEN`,
      value: `3302`,
      label: `ALTO DEL CARMEN`,
      cod_reg: `3`,
      nom_reg: `ATACAMA`,
    },
    {
      id: `3102`,
      nombre: `CALDERA`,
      value: `3102`,
      label: `CALDERA`,
      cod_reg: `3`,
      nom_reg: `ATACAMA`,
    },
    {
      id: `3201`,
      nombre: `CHAÑARAL`,
      value: `3201`,
      label: `CHAÑARAL`,
      cod_reg: `3`,
      nom_reg: `ATACAMA`,
    },
    {
      id: `3101`,
      nombre: `COPIAPÓ`,
      value: `3101`,
      label: `COPIAPÓ`,
      cod_reg: `3`,
      nom_reg: `ATACAMA`,
    },
    {
      id: `3202`,
      nombre: `DIEGO DE ALMAGRO`,
      value: `3202`,
      label: `DIEGO DE ALMAGRO`,
      cod_reg: `3`,
      nom_reg: `ATACAMA`,
    },
    {
      id: `3303`,
      nombre: `FREIRINA`,
      value: `3303`,
      label: `FREIRINA`,
      cod_reg: `3`,
      nom_reg: `ATACAMA`,
    },
    {
      id: `3304`,
      nombre: `HUASCO`,
      value: `3304`,
      label: `HUASCO`,
      cod_reg: `3`,
      nom_reg: `ATACAMA`,
    },
    {
      id: `3103`,
      nombre: `TIERRA AMARILLA`,
      value: `3103`,
      label: `TIERRA AMARILLA`,
      cod_reg: `3`,
      nom_reg: `ATACAMA`,
    },
    {
      id: `3301`,
      nombre: `VALLENAR`,
      value: `3301`,
      label: `VALLENAR`,
      cod_reg: `3`,
      nom_reg: `ATACAMA`,
    },
  ],
  '4': [
    {
      id: `4103`,
      nombre: `ANDACOLLO`,
      value: `4103`,
      label: `ANDACOLLO`,
      cod_reg: `4`,
      nom_reg: `COQUIMBO`,
    },
    {
      id: `4202`,
      nombre: `CANELA`,
      value: `4202`,
      label: `CANELA`,
      cod_reg: `4`,
      nom_reg: `COQUIMBO`,
    },
    {
      id: `4302`,
      nombre: `COMBARBALÁ`,
      value: `4302`,
      label: `COMBARBALÁ`,
      cod_reg: `4`,
      nom_reg: `COQUIMBO`,
    },
    {
      id: `4102`,
      nombre: `COQUIMBO`,
      value: `4102`,
      label: `COQUIMBO`,
      cod_reg: `4`,
      nom_reg: `COQUIMBO`,
    },
    {
      id: `4201`,
      nombre: `ILLAPEL`,
      value: `4201`,
      label: `ILLAPEL`,
      cod_reg: `4`,
      nom_reg: `COQUIMBO`,
    },
    {
      id: `4104`,
      nombre: `LA HIGUERA`,
      value: `4104`,
      label: `LA HIGUERA`,
      cod_reg: `4`,
      nom_reg: `COQUIMBO`,
    },
    {
      id: `4101`,
      nombre: `LA SERENA`,
      value: `4101`,
      label: `LA SERENA`,
      cod_reg: `4`,
      nom_reg: `COQUIMBO`,
    },
    {
      id: `4203`,
      nombre: `LOS VILOS`,
      value: `4203`,
      label: `LOS VILOS`,
      cod_reg: `4`,
      nom_reg: `COQUIMBO`,
    },
    {
      id: `4303`,
      nombre: `MONTE PATRIA`,
      value: `4303`,
      label: `MONTE PATRIA`,
      cod_reg: `4`,
      nom_reg: `COQUIMBO`,
    },
    {
      id: `4301`,
      nombre: `OVALLE`,
      value: `4301`,
      label: `OVALLE`,
      cod_reg: `4`,
      nom_reg: `COQUIMBO`,
    },
    {
      id: `4105`,
      nombre: `PAIGUANO`,
      value: `4105`,
      label: `PAIGUANO`,
      cod_reg: `4`,
      nom_reg: `COQUIMBO`,
    },
    {
      id: `4304`,
      nombre: `PUNITAQUI`,
      value: `4304`,
      label: `PUNITAQUI`,
      cod_reg: `4`,
      nom_reg: `COQUIMBO`,
    },
    {
      id: `4305`,
      nombre: `RÍO HURTADO`,
      value: `4305`,
      label: `RÍO HURTADO`,
      cod_reg: `4`,
      nom_reg: `COQUIMBO`,
    },
    {
      id: `4204`,
      nombre: `SALAMANCA`,
      value: `4204`,
      label: `SALAMANCA`,
      cod_reg: `4`,
      nom_reg: `COQUIMBO`,
    },
    {
      id: `4106`,
      nombre: `VICUÑA`,
      value: `4106`,
      label: `VICUÑA`,
      cod_reg: `4`,
      nom_reg: `COQUIMBO`,
    },
  ],
  '5': [
    {
      id: `5602`,
      nombre: `ALGARROBO`,
      value: `5602`,
      label: `ALGARROBO`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5402`,
      nombre: `CABILDO`,
      value: `5402`,
      label: `CABILDO`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5502`,
      nombre: `CALERA`,
      value: `5502`,
      label: `CALERA`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5302`,
      nombre: `CALLE LARGA`,
      value: `5302`,
      label: `CALLE LARGA`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5603`,
      nombre: `CARTAGENA`,
      value: `5603`,
      label: `CARTAGENA`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5102`,
      nombre: `CASABLANCA`,
      value: `5102`,
      label: `CASABLANCA`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5702`,
      nombre: `CATEMU`,
      value: `5702`,
      label: `CATEMU`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5103`,
      nombre: `CONCÓN`,
      value: `5103`,
      label: `CONCÓN`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5604`,
      nombre: `EL QUISCO`,
      value: `5604`,
      label: `EL QUISCO`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5605`,
      nombre: `EL TABO`,
      value: `5605`,
      label: `EL TABO`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5503`,
      nombre: `HIJUELAS`,
      value: `5503`,
      label: `HIJUELAS`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5201`,
      nombre: `ISLA DE PASCUA`,
      value: `5201`,
      label: `ISLA DE PASCUA`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5104`,
      nombre: `JUAN FERNÁNDEZ`,
      value: `5104`,
      label: `JUAN FERNÁNDEZ`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5504`,
      nombre: `LA CRUZ`,
      value: `5504`,
      label: `LA CRUZ`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5401`,
      nombre: `LA LIGUA`,
      value: `5401`,
      label: `LA LIGUA`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5802`,
      nombre: `LIMACHE`,
      value: `5802`,
      label: `LIMACHE`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5703`,
      nombre: `LLAILLAY`,
      value: `5703`,
      label: `LLAILLAY`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5301`,
      nombre: `LOS ANDES`,
      value: `5301`,
      label: `LOS ANDES`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5506`,
      nombre: `NOGALES`,
      value: `5506`,
      label: `NOGALES`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5803`,
      nombre: `OLMUÉ`,
      value: `5803`,
      label: `OLMUÉ`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5704`,
      nombre: `PANQUEHUE`,
      value: `5704`,
      label: `PANQUEHUE`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5403`,
      nombre: `PAPUDO`,
      value: `5403`,
      label: `PAPUDO`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5404`,
      nombre: `PETORCA`,
      value: `5404`,
      label: `PETORCA`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5105`,
      nombre: `PUCHUNCAVÍ`,
      value: `5105`,
      label: `PUCHUNCAVÍ`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5705`,
      nombre: `PUTAENDO`,
      value: `5705`,
      label: `PUTAENDO`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5501`,
      nombre: `QUILLOTA`,
      value: `5501`,
      label: `QUILLOTA`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5801`,
      nombre: `QUILPUÉ`,
      value: `5801`,
      label: `QUILPUÉ`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5107`,
      nombre: `QUINTERO`,
      value: `5107`,
      label: `QUINTERO`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5303`,
      nombre: `RINCONADA`,
      value: `5303`,
      label: `RINCONADA`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5601`,
      nombre: `SAN ANTONIO`,
      value: `5601`,
      label: `SAN ANTONIO`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5304`,
      nombre: `SAN ESTEBAN`,
      value: `5304`,
      label: `SAN ESTEBAN`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5701`,
      nombre: `SAN FELIPE`,
      value: `5701`,
      label: `SAN FELIPE`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5706`,
      nombre: `SANTA MARÍA`,
      value: `5706`,
      label: `SANTA MARÍA`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5606`,
      nombre: `SANTO DOMINGO`,
      value: `5606`,
      label: `SANTO DOMINGO`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5101`,
      nombre: `VALPARAÍSO`,
      value: `5101`,
      label: `VALPARAÍSO`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5804`,
      nombre: `VILLA ALEMANA`,
      value: `5804`,
      label: `VILLA ALEMANA`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5109`,
      nombre: `VIÑA DEL MAR`,
      value: `5109`,
      label: `VIÑA DEL MAR`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
    {
      id: `5405`,
      nombre: `ZAPALLAR`,
      value: `5405`,
      label: `ZAPALLAR`,
      cod_reg: `5`,
      nom_reg: `VALPARAÍSO`,
    },
  ],
  '6': [
    {
      id: `6303`,
      nombre: `CHIMBARONGO`,
      value: `6303`,
      label: `CHIMBARONGO`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6302`,
      nombre: `CHÉPICA`,
      value: `6302`,
      label: `CHÉPICA`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6102`,
      nombre: `CODEGUA`,
      value: `6102`,
      label: `CODEGUA`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6103`,
      nombre: `COINCO`,
      value: `6103`,
      label: `COINCO`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6104`,
      nombre: `COLTAUCO`,
      value: `6104`,
      label: `COLTAUCO`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6105`,
      nombre: `DOÑIHUE`,
      value: `6105`,
      label: `DOÑIHUE`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6106`,
      nombre: `GRANEROS`,
      value: `6106`,
      label: `GRANEROS`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6202`,
      nombre: `LA ESTRELLA`,
      value: `6202`,
      label: `LA ESTRELLA`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6107`,
      nombre: `LAS CABRAS`,
      value: `6107`,
      label: `LAS CABRAS`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6203`,
      nombre: `LITUECHE`,
      value: `6203`,
      label: `LITUECHE`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6304`,
      nombre: `LOLOL`,
      value: `6304`,
      label: `LOLOL`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6108`,
      nombre: `MACHALÍ`,
      value: `6108`,
      label: `MACHALÍ`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6109`,
      nombre: `MALLOA`,
      value: `6109`,
      label: `MALLOA`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6204`,
      nombre: `MARCHIHUE`,
      value: `6204`,
      label: `MARCHIHUE`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6110`,
      nombre: `MOSTAZAL`,
      value: `6110`,
      label: `MOSTAZAL`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6305`,
      nombre: `NANCAGUA`,
      value: `6305`,
      label: `NANCAGUA`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6205`,
      nombre: `NAVIDAD`,
      value: `6205`,
      label: `NAVIDAD`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6111`,
      nombre: `OLIVAR`,
      value: `6111`,
      label: `OLIVAR`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6306`,
      nombre: `PALMILLA`,
      value: `6306`,
      label: `PALMILLA`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6206`,
      nombre: `PAREDONES`,
      value: `6206`,
      label: `PAREDONES`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6307`,
      nombre: `PERALILLO`,
      value: `6307`,
      label: `PERALILLO`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6112`,
      nombre: `PEUMO`,
      value: `6112`,
      label: `PEUMO`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6113`,
      nombre: `PICHIDEGUA`,
      value: `6113`,
      label: `PICHIDEGUA`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6201`,
      nombre: `PICHILEMU`,
      value: `6201`,
      label: `PICHILEMU`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6308`,
      nombre: `PLACILLA`,
      value: `6308`,
      label: `PLACILLA`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6309`,
      nombre: `PUMANQUE`,
      value: `6309`,
      label: `PUMANQUE`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6114`,
      nombre: `QUINTA DE TILCOCO`,
      value: `6114`,
      label: `QUINTA DE TILCOCO`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6101`,
      nombre: `RANCAGUA`,
      value: `6101`,
      label: `RANCAGUA`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6115`,
      nombre: `RENGO`,
      value: `6115`,
      label: `RENGO`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6116`,
      nombre: `REQUÍNOA`,
      value: `6116`,
      label: `REQUÍNOA`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6301`,
      nombre: `SAN FERNANDO`,
      value: `6301`,
      label: `SAN FERNANDO`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6117`,
      nombre: `SAN VICENTE`,
      value: `6117`,
      label: `SAN VICENTE`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
    {
      id: `6310`,
      nombre: `SANTA CRUZ`,
      value: `6310`,
      label: `SANTA CRUZ`,
      cod_reg: `6`,
      nom_reg: `LIBERTADOR GRAL.BERNARDO O’HIGGINS`,
    },
  ],
  '7': [
    {
      id: `7201`,
      nombre: `CAUQUENES`,
      value: `7201`,
      label: `CAUQUENES`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7202`,
      nombre: `CHANCO`,
      value: `7202`,
      label: `CHANCO`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7402`,
      nombre: `COLBÚN`,
      value: `7402`,
      label: `COLBÚN`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7102`,
      nombre: `CONSTITUCIÓN`,
      value: `7102`,
      label: `CONSTITUCIÓN`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7103`,
      nombre: `CUREPTO`,
      value: `7103`,
      label: `CUREPTO`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7301`,
      nombre: `CURICÓ`,
      value: `7301`,
      label: `CURICÓ`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7104`,
      nombre: `EMPEDRADO`,
      value: `7104`,
      label: `EMPEDRADO`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7302`,
      nombre: `HUALAÑÉ`,
      value: `7302`,
      label: `HUALAÑÉ`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7303`,
      nombre: `LICANTÉN`,
      value: `7303`,
      label: `LICANTÉN`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7401`,
      nombre: `LINARES`,
      value: `7401`,
      label: `LINARES`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7403`,
      nombre: `LONGAVÍ`,
      value: `7403`,
      label: `LONGAVÍ`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7105`,
      nombre: `MAULE`,
      value: `7105`,
      label: `MAULE`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7304`,
      nombre: `MOLINA`,
      value: `7304`,
      label: `MOLINA`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7404`,
      nombre: `PARRAL`,
      value: `7404`,
      label: `PARRAL`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7106`,
      nombre: `PELARCO`,
      value: `7106`,
      label: `PELARCO`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7203`,
      nombre: `PELLUHUE`,
      value: `7203`,
      label: `PELLUHUE`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7107`,
      nombre: `PENCAHUE`,
      value: `7107`,
      label: `PENCAHUE`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7305`,
      nombre: `RAUCO`,
      value: `7305`,
      label: `RAUCO`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7405`,
      nombre: `RETIRO`,
      value: `7405`,
      label: `RETIRO`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7306`,
      nombre: `ROMERAL`,
      value: `7306`,
      label: `ROMERAL`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7108`,
      nombre: `RÍO CLARO`,
      value: `7108`,
      label: `RÍO CLARO`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7307`,
      nombre: `SAGRADA FAMILIA`,
      value: `7307`,
      label: `SAGRADA FAMILIA`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7109`,
      nombre: `SAN CLEMENTE`,
      value: `7109`,
      label: `SAN CLEMENTE`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7406`,
      nombre: `SAN JAVIER`,
      value: `7406`,
      label: `SAN JAVIER`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7110`,
      nombre: `SAN RAFAEL`,
      value: `7110`,
      label: `SAN RAFAEL`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7101`,
      nombre: `TALCA`,
      value: `7101`,
      label: `TALCA`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7308`,
      nombre: `TENO`,
      value: `7308`,
      label: `TENO`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7309`,
      nombre: `VICHUQUÉN`,
      value: `7309`,
      label: `VICHUQUÉN`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7407`,
      nombre: `VILLA ALEGRE`,
      value: `7407`,
      label: `VILLA ALEGRE`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
    {
      id: `7408`,
      nombre: `YERBAS BUENAS`,
      value: `7408`,
      label: `YERBAS BUENAS`,
      cod_reg: `7`,
      nom_reg: `MAULE`,
    },
  ],
  '8': [
    {
      id: `8314`,
      nombre: `ALTO BIOBÍO`,
      value: `8314`,
      label: `ALTO BIOBÍO`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8302`,
      nombre: `ANTUCO`,
      value: `8302`,
      label: `ANTUCO`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8202`,
      nombre: `ARAUCO`,
      value: `8202`,
      label: `ARAUCO`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8303`,
      nombre: `CABRERO`,
      value: `8303`,
      label: `CABRERO`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8203`,
      nombre: `CAÑETE`,
      value: `8203`,
      label: `CAÑETE`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8103`,
      nombre: `CHIGUAYANTE`,
      value: `8103`,
      label: `CHIGUAYANTE`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8101`,
      nombre: `CONCEPCIÓN`,
      value: `8101`,
      label: `CONCEPCIÓN`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8204`,
      nombre: `CONTULMO`,
      value: `8204`,
      label: `CONTULMO`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8102`,
      nombre: `CORONEL`,
      value: `8102`,
      label: `CORONEL`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8205`,
      nombre: `CURANILAHUE`,
      value: `8205`,
      label: `CURANILAHUE`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8104`,
      nombre: `FLORIDA`,
      value: `8104`,
      label: `FLORIDA`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8112`,
      nombre: `HUALPÉN`,
      value: `8112`,
      label: `HUALPÉN`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8105`,
      nombre: `HUALQUI`,
      value: `8105`,
      label: `HUALQUI`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8304`,
      nombre: `LAJA`,
      value: `8304`,
      label: `LAJA`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8201`,
      nombre: `LEBU`,
      value: `8201`,
      label: `LEBU`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8206`,
      nombre: `LOS ÁLAMOS`,
      value: `8206`,
      label: `LOS ÁLAMOS`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8301`,
      nombre: `LOS ÁNGELES`,
      value: `8301`,
      label: `LOS ÁNGELES`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8106`,
      nombre: `LOTA`,
      value: `8106`,
      label: `LOTA`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8305`,
      nombre: `MULCHÉN`,
      value: `8305`,
      label: `MULCHÉN`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8306`,
      nombre: `NACIMIENTO`,
      value: `8306`,
      label: `NACIMIENTO`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8307`,
      nombre: `NEGRETE`,
      value: `8307`,
      label: `NEGRETE`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8107`,
      nombre: `PENCO`,
      value: `8107`,
      label: `PENCO`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8308`,
      nombre: `QUILACO`,
      value: `8308`,
      label: `QUILACO`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8309`,
      nombre: `QUILLECO`,
      value: `8309`,
      label: `QUILLECO`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8108`,
      nombre: `SAN PEDRO DE LA PAZ`,
      value: `8108`,
      label: `SAN PEDRO DE LA PAZ`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8310`,
      nombre: `SAN ROSENDO`,
      value: `8310`,
      label: `SAN ROSENDO`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8311`,
      nombre: `SANTA BÁRBARA`,
      value: `8311`,
      label: `SANTA BÁRBARA`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8109`,
      nombre: `SANTA JUANA`,
      value: `8109`,
      label: `SANTA JUANA`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8110`,
      nombre: `TALCAHUANO`,
      value: `8110`,
      label: `TALCAHUANO`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8207`,
      nombre: `TIRÚA`,
      value: `8207`,
      label: `TIRÚA`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8111`,
      nombre: `TOMÉ`,
      value: `8111`,
      label: `TOMÉ`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8312`,
      nombre: `TUCAPEL`,
      value: `8312`,
      label: `TUCAPEL`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
    {
      id: `8313`,
      nombre: `YUMBEL`,
      value: `8313`,
      label: `YUMBEL`,
      cod_reg: `8`,
      nom_reg: `BIOBÍO`,
    },
  ],
  '9': [
    {
      id: `9201`,
      nombre: `ANGOL`,
      value: `9201`,
      label: `ANGOL`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9102`,
      nombre: `CARAHUE`,
      value: `9102`,
      label: `CARAHUE`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9121`,
      nombre: `CHOLCHOL`,
      value: `9121`,
      label: `CHOLCHOL`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9202`,
      nombre: `COLLIPULLI`,
      value: `9202`,
      label: `COLLIPULLI`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9103`,
      nombre: `CUNCO`,
      value: `9103`,
      label: `CUNCO`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9203`,
      nombre: `CURACAUTÍN`,
      value: `9203`,
      label: `CURACAUTÍN`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9104`,
      nombre: `CURARREHUE`,
      value: `9104`,
      label: `CURARREHUE`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9204`,
      nombre: `ERCILLA`,
      value: `9204`,
      label: `ERCILLA`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9105`,
      nombre: `FREIRE`,
      value: `9105`,
      label: `FREIRE`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9106`,
      nombre: `GALVARINO`,
      value: `9106`,
      label: `GALVARINO`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9107`,
      nombre: `GORBEA`,
      value: `9107`,
      label: `GORBEA`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9108`,
      nombre: `LAUTARO`,
      value: `9108`,
      label: `LAUTARO`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9109`,
      nombre: `LONCOCHE`,
      value: `9109`,
      label: `LONCOCHE`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9205`,
      nombre: `LONQUIMAY`,
      value: `9205`,
      label: `LONQUIMAY`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9206`,
      nombre: `LOS SAUCES`,
      value: `9206`,
      label: `LOS SAUCES`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9207`,
      nombre: `LUMACO`,
      value: `9207`,
      label: `LUMACO`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9110`,
      nombre: `MELIPEUCO`,
      value: `9110`,
      label: `MELIPEUCO`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9111`,
      nombre: `NUEVA IMPERIAL`,
      value: `9111`,
      label: `NUEVA IMPERIAL`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9112`,
      nombre: `PADRE LAS CASAS`,
      value: `9112`,
      label: `PADRE LAS CASAS`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9113`,
      nombre: `PERQUENCO`,
      value: `9113`,
      label: `PERQUENCO`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9114`,
      nombre: `PITRUFQUÉN`,
      value: `9114`,
      label: `PITRUFQUÉN`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9115`,
      nombre: `PUCÓN`,
      value: `9115`,
      label: `PUCÓN`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9208`,
      nombre: `PURÉN`,
      value: `9208`,
      label: `PURÉN`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9209`,
      nombre: `RENAICO`,
      value: `9209`,
      label: `RENAICO`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9116`,
      nombre: `SAAVEDRA`,
      value: `9116`,
      label: `SAAVEDRA`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9101`,
      nombre: `TEMUCO`,
      value: `9101`,
      label: `TEMUCO`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9117`,
      nombre: `TEODORO SCHMIDT`,
      value: `9117`,
      label: `TEODORO SCHMIDT`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9118`,
      nombre: `TOLTÉN`,
      value: `9118`,
      label: `TOLTÉN`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9210`,
      nombre: `TRAIGUÉN`,
      value: `9210`,
      label: `TRAIGUÉN`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9211`,
      nombre: `VICTORIA`,
      value: `9211`,
      label: `VICTORIA`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9119`,
      nombre: `VILCÚN`,
      value: `9119`,
      label: `VILCÚN`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
    {
      id: `9120`,
      nombre: `VILLARRICA`,
      value: `9120`,
      label: `VILLARRICA`,
      cod_reg: `9`,
      nom_reg: `LA ARAUCANÍA`,
    },
  ],
  '10': [
    {
      id: `10202`,
      nombre: `ANCUD`,
      value: `10202`,
      label: `ANCUD`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10102`,
      nombre: `CALBUCO`,
      value: `10102`,
      label: `CALBUCO`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10201`,
      nombre: `CASTRO`,
      value: `10201`,
      label: `CASTRO`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10401`,
      nombre: `CHAITÉN`,
      value: `10401`,
      label: `CHAITÉN`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10203`,
      nombre: `CHONCHI`,
      value: `10203`,
      label: `CHONCHI`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10103`,
      nombre: `COCHAMÓ`,
      value: `10103`,
      label: `COCHAMÓ`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10204`,
      nombre: `CURACO DE VÉLEZ`,
      value: `10204`,
      label: `CURACO DE VÉLEZ`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10205`,
      nombre: `DALCAHUE`,
      value: `10205`,
      label: `DALCAHUE`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10104`,
      nombre: `FRESIA`,
      value: `10104`,
      label: `FRESIA`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10105`,
      nombre: `FRUTILLAR`,
      value: `10105`,
      label: `FRUTILLAR`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10402`,
      nombre: `FUTALEUFÚ`,
      value: `10402`,
      label: `FUTALEUFÚ`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10403`,
      nombre: `HUALAIHUÉ`,
      value: `10403`,
      label: `HUALAIHUÉ`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10107`,
      nombre: `LLANQUIHUE`,
      value: `10107`,
      label: `LLANQUIHUE`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10106`,
      nombre: `LOS MUERMOS`,
      value: `10106`,
      label: `LOS MUERMOS`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10108`,
      nombre: `MAULLÍN`,
      value: `10108`,
      label: `MAULLÍN`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10301`,
      nombre: `OSORNO`,
      value: `10301`,
      label: `OSORNO`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10404`,
      nombre: `PALENA`,
      value: `10404`,
      label: `PALENA`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10101`,
      nombre: `PUERTO MONTT`,
      value: `10101`,
      label: `PUERTO MONTT`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10302`,
      nombre: `PUERTO OCTAY`,
      value: `10302`,
      label: `PUERTO OCTAY`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10109`,
      nombre: `PUERTO VARAS`,
      value: `10109`,
      label: `PUERTO VARAS`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10206`,
      nombre: `PUQUELDÓN`,
      value: `10206`,
      label: `PUQUELDÓN`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10303`,
      nombre: `PURRANQUE`,
      value: `10303`,
      label: `PURRANQUE`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10304`,
      nombre: `PUYEHUE`,
      value: `10304`,
      label: `PUYEHUE`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10207`,
      nombre: `QUEILÉN`,
      value: `10207`,
      label: `QUEILÉN`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10208`,
      nombre: `QUELLÓN`,
      value: `10208`,
      label: `QUELLÓN`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10209`,
      nombre: `QUEMCHI`,
      value: `10209`,
      label: `QUEMCHI`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10210`,
      nombre: `QUINCHAO`,
      value: `10210`,
      label: `QUINCHAO`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10305`,
      nombre: `RÍO NEGRO`,
      value: `10305`,
      label: `RÍO NEGRO`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10306`,
      nombre: `SAN JUAN DE LA COSTA`,
      value: `10306`,
      label: `SAN JUAN DE LA COSTA`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
    {
      id: `10307`,
      nombre: `SAN PABLO`,
      value: `10307`,
      label: `SAN PABLO`,
      cod_reg: `10`,
      nom_reg: `LOS LAGOS`,
    },
  ],
  '11': [
    {
      id: `11201`,
      nombre: `AYSÉN`,
      value: `11201`,
      label: `AYSÉN`,
      cod_reg: `11`,
      nom_reg: `AYSÉN DEL GRAL. CARLOS IBÁÑEZ DEL CAMPO`,
    },
    {
      id: `11401`,
      nombre: `CHILE CHICO`,
      value: `11401`,
      label: `CHILE CHICO`,
      cod_reg: `11`,
      nom_reg: `AYSÉN DEL GRAL. CARLOS IBÁÑEZ DEL CAMPO`,
    },
    {
      id: `11202`,
      nombre: `CISNES`,
      value: `11202`,
      label: `CISNES`,
      cod_reg: `11`,
      nom_reg: `AYSÉN DEL GRAL. CARLOS IBÁÑEZ DEL CAMPO`,
    },
    {
      id: `11301`,
      nombre: `COCHRANE`,
      value: `11301`,
      label: `COCHRANE`,
      cod_reg: `11`,
      nom_reg: `AYSÉN DEL GRAL. CARLOS IBÁÑEZ DEL CAMPO`,
    },
    {
      id: `11101`,
      nombre: `COYHAIQUE`,
      value: `11101`,
      label: `COYHAIQUE`,
      cod_reg: `11`,
      nom_reg: `AYSÉN DEL GRAL. CARLOS IBÁÑEZ DEL CAMPO`,
    },
    {
      id: `11203`,
      nombre: `GUAITECAS`,
      value: `11203`,
      label: `GUAITECAS`,
      cod_reg: `11`,
      nom_reg: `AYSÉN DEL GRAL. CARLOS IBÁÑEZ DEL CAMPO`,
    },
    {
      id: `11102`,
      nombre: `LAGO VERDE`,
      value: `11102`,
      label: `LAGO VERDE`,
      cod_reg: `11`,
      nom_reg: `AYSÉN DEL GRAL. CARLOS IBÁÑEZ DEL CAMPO`,
    },
    {
      id: `11302`,
      nombre: `O’HIGGINS`,
      value: `11302`,
      label: `O’HIGGINS`,
      cod_reg: `11`,
      nom_reg: `AYSÉN DEL GRAL. CARLOS IBÁÑEZ DEL CAMPO`,
    },
    {
      id: `11402`,
      nombre: `RÍO IBÁÑEZ`,
      value: `11402`,
      label: `RÍO IBÁÑEZ`,
      cod_reg: `11`,
      nom_reg: `AYSÉN DEL GRAL. CARLOS IBÁÑEZ DEL CAMPO`,
    },
    {
      id: `11303`,
      nombre: `TORTEL`,
      value: `11303`,
      label: `TORTEL`,
      cod_reg: `11`,
      nom_reg: `AYSÉN DEL GRAL. CARLOS IBÁÑEZ DEL CAMPO`,
    },
  ],
  '12': [
    {
      id: `12202`,
      nombre: `ANTÁRTICA`,
      value: `12202`,
      label: `ANTÁRTICA`,
      cod_reg: `12`,
      nom_reg: `MAGALLANES Y DE LA ANTÁRTICA CHILENA`,
    },
    {
      id: `12201`,
      nombre: `CABO DE HORNOS (EX - NAVARINO)`,
      value: `12201`,
      label: `CABO DE HORNOS (EX - NAVARINO)`,
      cod_reg: `12`,
      nom_reg: `MAGALLANES Y DE LA ANTÁRTICA CHILENA`,
    },
    {
      id: `12102`,
      nombre: `LAGUNA BLANCA`,
      value: `12102`,
      label: `LAGUNA BLANCA`,
      cod_reg: `12`,
      nom_reg: `MAGALLANES Y DE LA ANTÁRTICA CHILENA`,
    },
    {
      id: `12401`,
      nombre: `NATALES`,
      value: `12401`,
      label: `NATALES`,
      cod_reg: `12`,
      nom_reg: `MAGALLANES Y DE LA ANTÁRTICA CHILENA`,
    },
    {
      id: `12301`,
      nombre: `PORVENIR`,
      value: `12301`,
      label: `PORVENIR`,
      cod_reg: `12`,
      nom_reg: `MAGALLANES Y DE LA ANTÁRTICA CHILENA`,
    },
    {
      id: `12302`,
      nombre: `PRIMAVERA`,
      value: `12302`,
      label: `PRIMAVERA`,
      cod_reg: `12`,
      nom_reg: `MAGALLANES Y DE LA ANTÁRTICA CHILENA`,
    },
    {
      id: `12101`,
      nombre: `PUNTA ARENAS`,
      value: `12101`,
      label: `PUNTA ARENAS`,
      cod_reg: `12`,
      nom_reg: `MAGALLANES Y DE LA ANTÁRTICA CHILENA`,
    },
    {
      id: `12103`,
      nombre: `RÍO VERDE`,
      value: `12103`,
      label: `RÍO VERDE`,
      cod_reg: `12`,
      nom_reg: `MAGALLANES Y DE LA ANTÁRTICA CHILENA`,
    },
    {
      id: `12104`,
      nombre: `SAN GREGORIO`,
      value: `12104`,
      label: `SAN GREGORIO`,
      cod_reg: `12`,
      nom_reg: `MAGALLANES Y DE LA ANTÁRTICA CHILENA`,
    },
    {
      id: `12303`,
      nombre: `TIMAUKEL`,
      value: `12303`,
      label: `TIMAUKEL`,
      cod_reg: `12`,
      nom_reg: `MAGALLANES Y DE LA ANTÁRTICA CHILENA`,
    },
    {
      id: `12402`,
      nombre: `TORRES DEL PAINE`,
      value: `12402`,
      label: `TORRES DEL PAINE`,
      cod_reg: `12`,
      nom_reg: `MAGALLANES Y DE LA ANTÁRTICA CHILENA`,
    },
  ],
  '13': [
    {
      id: `13502`,
      nombre: `ALHUÉ`,
      value: `13502`,
      label: `ALHUÉ`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13402`,
      nombre: `BUIN`,
      value: `13402`,
      label: `BUIN`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13403`,
      nombre: `CALERA DE TANGO`,
      value: `13403`,
      label: `CALERA DE TANGO`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13102`,
      nombre: `CERRILLOS`,
      value: `13102`,
      label: `CERRILLOS`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13103`,
      nombre: `CERRO NAVIA`,
      value: `13103`,
      label: `CERRO NAVIA`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13301`,
      nombre: `COLINA`,
      value: `13301`,
      label: `COLINA`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13104`,
      nombre: `CONCHALÍ`,
      value: `13104`,
      label: `CONCHALÍ`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13503`,
      nombre: `CURACAVÍ`,
      value: `13503`,
      label: `CURACAVÍ`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13105`,
      nombre: `EL BOSQUE`,
      value: `13105`,
      label: `EL BOSQUE`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13602`,
      nombre: `EL MONTE`,
      value: `13602`,
      label: `EL MONTE`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13106`,
      nombre: `ESTACIÓN CENTRAL`,
      value: `13106`,
      label: `ESTACIÓN CENTRAL`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13107`,
      nombre: `HUECHURABA`,
      value: `13107`,
      label: `HUECHURABA`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13108`,
      nombre: `INDEPENDENCIA`,
      value: `13108`,
      label: `INDEPENDENCIA`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13603`,
      nombre: `ISLA DE MAIPO`,
      value: `13603`,
      label: `ISLA DE MAIPO`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13109`,
      nombre: `LA CISTERNA`,
      value: `13109`,
      label: `LA CISTERNA`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13110`,
      nombre: `LA FLORIDA`,
      value: `13110`,
      label: `LA FLORIDA`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13111`,
      nombre: `LA GRANJA`,
      value: `13111`,
      label: `LA GRANJA`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13112`,
      nombre: `LA PINTANA`,
      value: `13112`,
      label: `LA PINTANA`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13113`,
      nombre: `LA REINA`,
      value: `13113`,
      label: `LA REINA`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13302`,
      nombre: `LAMPA`,
      value: `13302`,
      label: `LAMPA`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13114`,
      nombre: `LAS CONDES`,
      value: `13114`,
      label: `LAS CONDES`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13115`,
      nombre: `LO BARNECHEA`,
      value: `13115`,
      label: `LO BARNECHEA`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13116`,
      nombre: `LO ESPEJO`,
      value: `13116`,
      label: `LO ESPEJO`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13117`,
      nombre: `LO PRADO`,
      value: `13117`,
      label: `LO PRADO`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13118`,
      nombre: `MACUL`,
      value: `13118`,
      label: `MACUL`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13119`,
      nombre: `MAIPÚ`,
      value: `13119`,
      label: `MAIPÚ`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13504`,
      nombre: `MARÍA PINTO`,
      value: `13504`,
      label: `MARÍA PINTO`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13501`,
      nombre: `MELIPILLA`,
      value: `13501`,
      label: `MELIPILLA`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13604`,
      nombre: `PADRE HURTADO`,
      value: `13604`,
      label: `PADRE HURTADO`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13404`,
      nombre: `PAINE`,
      value: `13404`,
      label: `PAINE`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13121`,
      nombre: `PEDRO AGUIRRE CERDA`,
      value: `13121`,
      label: `PEDRO AGUIRRE CERDA`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13605`,
      nombre: `PEÑAFLOR`,
      value: `13605`,
      label: `PEÑAFLOR`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13122`,
      nombre: `PEÑALOLÉN`,
      value: `13122`,
      label: `PEÑALOLÉN`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13202`,
      nombre: `PIRQUE`,
      value: `13202`,
      label: `PIRQUE`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13123`,
      nombre: `PROVIDENCIA`,
      value: `13123`,
      label: `PROVIDENCIA`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13124`,
      nombre: `PUDAHUEL`,
      value: `13124`,
      label: `PUDAHUEL`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13201`,
      nombre: `PUENTE ALTO`,
      value: `13201`,
      label: `PUENTE ALTO`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13125`,
      nombre: `QUILICURA`,
      value: `13125`,
      label: `QUILICURA`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13126`,
      nombre: `QUINTA NORMAL`,
      value: `13126`,
      label: `QUINTA NORMAL`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13127`,
      nombre: `RECOLETA`,
      value: `13127`,
      label: `RECOLETA`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13128`,
      nombre: `RENCA`,
      value: `13128`,
      label: `RENCA`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13401`,
      nombre: `SAN BERNARDO`,
      value: `13401`,
      label: `SAN BERNARDO`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13129`,
      nombre: `SAN JOAQUÍN`,
      value: `13129`,
      label: `SAN JOAQUÍN`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13203`,
      nombre: `SAN JOSÉ DE MAIPO`,
      value: `13203`,
      label: `SAN JOSÉ DE MAIPO`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13130`,
      nombre: `SAN MIGUEL`,
      value: `13130`,
      label: `SAN MIGUEL`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13505`,
      nombre: `SAN PEDRO`,
      value: `13505`,
      label: `SAN PEDRO`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13131`,
      nombre: `SAN RAMÓN`,
      value: `13131`,
      label: `SAN RAMÓN`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13101`,
      nombre: `SANTIAGO`,
      value: `13101`,
      label: `SANTIAGO`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13601`,
      nombre: `TALAGANTE`,
      value: `13601`,
      label: `TALAGANTE`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13303`,
      nombre: `TILTIL`,
      value: `13303`,
      label: `TILTIL`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13132`,
      nombre: `VITACURA`,
      value: `13132`,
      label: `VITACURA`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
    {
      id: `13120`,
      nombre: `ÑUÑOA`,
      value: `13120`,
      label: `ÑUÑOA`,
      cod_reg: `13`,
      nom_reg: `METROPOLITANA DE SANTIAGO`,
    },
  ],
  '14': [
    {
      id: `14102`,
      nombre: `CORRAL`,
      value: `14102`,
      label: `CORRAL`,
      cod_reg: `14`,
      nom_reg: `LOS RÍOS`,
    },
    {
      id: `14202`,
      nombre: `FUTRONO`,
      value: `14202`,
      label: `FUTRONO`,
      cod_reg: `14`,
      nom_reg: `LOS RÍOS`,
    },
    {
      id: `14201`,
      nombre: `LA UNIÓN`,
      value: `14201`,
      label: `LA UNIÓN`,
      cod_reg: `14`,
      nom_reg: `LOS RÍOS`,
    },
    {
      id: `14203`,
      nombre: `LAGO RANCO`,
      value: `14203`,
      label: `LAGO RANCO`,
      cod_reg: `14`,
      nom_reg: `LOS RÍOS`,
    },
    {
      id: `14103`,
      nombre: `LANCO`,
      value: `14103`,
      label: `LANCO`,
      cod_reg: `14`,
      nom_reg: `LOS RÍOS`,
    },
    {
      id: `14104`,
      nombre: `LOS LAGOS`,
      value: `14104`,
      label: `LOS LAGOS`,
      cod_reg: `14`,
      nom_reg: `LOS RÍOS`,
    },
    {
      id: `14106`,
      nombre: `MARIQUINA`,
      value: `14106`,
      label: `MARIQUINA`,
      cod_reg: `14`,
      nom_reg: `LOS RÍOS`,
    },
    {
      id: `14105`,
      nombre: `MÁFIL`,
      value: `14105`,
      label: `MÁFIL`,
      cod_reg: `14`,
      nom_reg: `LOS RÍOS`,
    },
    {
      id: `14107`,
      nombre: `PAILLACO`,
      value: `14107`,
      label: `PAILLACO`,
      cod_reg: `14`,
      nom_reg: `LOS RÍOS`,
    },
    {
      id: `14108`,
      nombre: `PANGUIPULLI`,
      value: `14108`,
      label: `PANGUIPULLI`,
      cod_reg: `14`,
      nom_reg: `LOS RÍOS`,
    },
    {
      id: `14204`,
      nombre: `RÍO BUENO`,
      value: `14204`,
      label: `RÍO BUENO`,
      cod_reg: `14`,
      nom_reg: `LOS RÍOS`,
    },
    {
      id: `14101`,
      nombre: `VALDIVIA`,
      value: `14101`,
      label: `VALDIVIA`,
      cod_reg: `14`,
      nom_reg: `LOS RÍOS`,
    },
  ],
  '15': [
    {
      id: `15101`,
      nombre: `ARICA`,
      value: `15101`,
      label: `ARICA`,
      cod_reg: `15`,
      nom_reg: `ARICA Y PARINACOTA`,
    },
    {
      id: `15102`,
      nombre: `CAMARONES`,
      value: `15102`,
      label: `CAMARONES`,
      cod_reg: `15`,
      nom_reg: `ARICA Y PARINACOTA`,
    },
    {
      id: `15202`,
      nombre: `GENERAL LAGOS`,
      value: `15202`,
      label: `GENERAL LAGOS`,
      cod_reg: `15`,
      nom_reg: `ARICA Y PARINACOTA`,
    },
    {
      id: `15201`,
      nombre: `PUTRE`,
      value: `15201`,
      label: `PUTRE`,
      cod_reg: `15`,
      nom_reg: `ARICA Y PARINACOTA`,
    },
  ],
  '16': [
    {
      id: `16102`,
      nombre: `BULNES`,
      value: `16102`,
      label: `BULNES`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
    {
      id: `16101`,
      nombre: `CHILLÁN`,
      value: `16101`,
      label: `CHILLÁN`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
    {
      id: `16103`,
      nombre: `CHILLÁN VIEJO`,
      value: `16103`,
      label: `CHILLÁN VIEJO`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
    {
      id: `16202`,
      nombre: `COBQUECURA`,
      value: `16202`,
      label: `COBQUECURA`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
    {
      id: `16203`,
      nombre: `COELEMU`,
      value: `16203`,
      label: `COELEMU`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
    {
      id: `16302`,
      nombre: `COIHUECO`,
      value: `16302`,
      label: `COIHUECO`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
    {
      id: `16104`,
      nombre: `EL CARMEN`,
      value: `16104`,
      label: `EL CARMEN`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
    {
      id: `16204`,
      nombre: `NINHUE`,
      value: `16204`,
      label: `NINHUE`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
    {
      id: `16105`,
      nombre: `PEMUCO`,
      value: `16105`,
      label: `PEMUCO`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
    {
      id: `16106`,
      nombre: `PINTO`,
      value: `16106`,
      label: `PINTO`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
    {
      id: `16205`,
      nombre: `PORTEZUELO`,
      value: `16205`,
      label: `PORTEZUELO`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
    {
      id: `16107`,
      nombre: `QUILLÓN`,
      value: `16107`,
      label: `QUILLÓN`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
    {
      id: `16201`,
      nombre: `QUIRIHUE`,
      value: `16201`,
      label: `QUIRIHUE`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
    {
      id: `16206`,
      nombre: `RÁNQUIL`,
      value: `16206`,
      label: `RÁNQUIL`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
    {
      id: `16301`,
      nombre: `SAN CARLOS`,
      value: `16301`,
      label: `SAN CARLOS`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
    {
      id: `16304`,
      nombre: `SAN FABIÁN`,
      value: `16304`,
      label: `SAN FABIÁN`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
    {
      id: `16108`,
      nombre: `SAN IGNACIO`,
      value: `16108`,
      label: `SAN IGNACIO`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
    {
      id: `16305`,
      nombre: `SAN NICOLÁS`,
      value: `16305`,
      label: `SAN NICOLÁS`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
    {
      id: `16207`,
      nombre: `TREGUACO`,
      value: `16207`,
      label: `TREGUACO`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
    {
      id: `16109`,
      nombre: `YUNGAY`,
      value: `16109`,
      label: `YUNGAY`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
    {
      id: `16303`,
      nombre: `ÑIQUÉN`,
      value: `16303`,
      label: `ÑIQUÉN`,
      cod_reg: `16`,
      nom_reg: `ÑUBLE`,
    },
  ],
}
